### PR TITLE
Allow all channels by default

### LINKED ISSUE #357: CondaStore.conda_allowed_channels should by default allow all channels
Why is 'allowed channels' hardcoded in:

https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/app.py

Can these be overridden in config. Why not allow any channel by default?

This relates to pr #354 as well since that I think isn't the ideal way to fix this issue.

@costrouc @iameskild

### PR DESCRIPTION
**Pull request by nkaretnikov**
Fixes #357.

### CODE REVIEW

**Comment by nkaretnikov** [comment]
Changed to empty list (allow all), added example that used to be the previous default, verified that this environment is accepted (with the empty list in allowed channels) and builds:

```yaml
channels:
- conda-forge
- https://repo.anaconda.com/pkgs/main
dependencies:
- pip
- pip:
  - nothing
- ipykernel
description: ''
name: test-env
prefix: null
variables: null
```

How it now looks in the web UI:

Screen Shot 2023-08-23 at 09 27 07

**Review by costrouc — APPROVED** [review]
LGTM. Thanks @nkaretnikov!

**Comment by nkaretnikov** [comment]
@costrouc I have no write access to the repo. Can you merge it? Or are we waiting for other approvals?

**Comment by costrouc** [comment]
Was waiting for the ci to pass just in case

**Pull request merged**
