### PR TITLE
Build docker images for arm (aarch64)

### LINKED ISSUE #821: [ENH] - Build docker images for arm (aarch64)
### Feature description

Build docker images for arm (`aarch64`) based machines.

### Value and/or benefit

Currently conda-store is building docker images only for `x86_64`, which would not work for `aarch64` machines. Implementing this issue will have the following benefits:

- Users will be able to chose arm based images in their cloud provider to run conda-store on.
- It will help developers run local deployment of Nebari (biggest consumer of conda-store) on Mac M1 (https://github.com/nebari-dev/nebari/issues/1405) or any arm based machines.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aktech**
Fixes #821 

## Description

This pull request:

- Add another matrix item in the CI to build docker images for arm.

## Pull request checklist

- [ ] Did you test this change locally?
- [ ] Did you update the documentation (if required)?
- [ ] Did you add/update relevant tests for this change (if required)?

### CODE REVIEW

**Comment by trallard** [comment]
@aktech this has been in WIP for a bit. Are you planning to continue to work on this PR?

**Comment by aktech** [comment]
Yes. The windows test failure is unrelated: https://github.com/conda-incubator/conda-store/actions/runs/9006701345/job/25302259825?pr=822

and the docker image build got stalled, needs to be re-triggered.

**Comment by aktech** [comment]
also, would need workflow trigger approval (potentially multiple times) to make it green

**Comment by peytondmurray** [comment]
Updated branch to trigger workflows, let's see if we can get this merged.

**Comment by aktech** [comment]
This is ready for review, CI is green now.

**Review by marcelovilla — APPROVED** [review]
Thanks @aktech 🚀 !

**Comment by marcelovilla** [comment]
@peytondmurray is there any reason not to approve this? I see you added the `needs: discussion` label.

**Comment by peytondmurray** [comment]
Nope, I'll merge it now - that label as added so I could easily filter for it during today's meeting.

**Review by peytondmurray — APPROVED** [review]
:rocket: Thanks for this!

**Pull request merged**
