### PR TITLE
[AUTO] - Update  docs screenshots

### PR DESCRIPTION
**Pull request by jaimergp**
Update screenshots
- Updated with the latest images from playwright generated in PR 346
- Auto-generated by [create-pull-request][1]

[1]: https://github.com/peter-evans/create-pull-request

### CODE REVIEW

**Comment by jaimergp** [comment]
Isn't this a bit weird that this action opens PRs on someone's behalf? I didn't submit this but somehow it ends up in my notifications 😬 

Can it be changed so it uses `github-actions[bot]` or something?

**Comment by jaimergp** [comment]
I guess this is due to my PAT token being used for the cross-repo submissions.

**Comment by trallard** [comment]
@kcpevey this has been opened for a while what needs doing?

**Comment by kcpevey** [comment]
The PR on the UI side needs to be finished up before this can be resolved. It has been open for an embarrassing amount of time - sorry!

**Pull request closed without merging**
