### PR TITLE
Adding support for installing pip packages using conda-docker

### PR DESCRIPTION
**Pull request by PhilipNeffOnGithub**

### CODE REVIEW

**Comment by dharhas** [comment]
@costrouc Can you review this when you are back. Or @pierrotsmnrd  or @aktech can one of you have a look.

@PhilipNeffOnGithub sorry for the delayed response.

**Comment by costrouc** [comment]
@PhilipNeffOnGithub I appreciate you opening this PR! Apologies for being on parental leave. I see that this PR depends on https://github.com/conda-incubator/conda-docker/pull/20 so I will look into that one first. On first pass thanks so much for this work. It will be a huge add to have support for pip within the docker images.

**Comment by costrouc** [comment]
Hey @PhilipNeffOnGithub I'll need to look at https://github.com/conda-incubator/conda-docker/pull/20 before merging this PR. It may take me awhile to review this PR.

**Comment by trallard** [comment]
This has been opened for almost two years with no movement. I will go ahead and close this PR and we can reopen or open a new one if there is need to add this.

**Pull request closed without merging**
