### PR TITLE
DEV -  Set a canonical default Python version (3.12)

### PR DESCRIPTION
**Pull request by trallard**
This is another stack to #838  and intended to be merged _after_ #841 

## Description

While reviewing #841, @peytondmurray suggested bumping the default Python version used for CI, Docker images, and the like.

This PR bumps us from `3.10` to `3.12`:

* Adds a `.python-version-default` file to serve as the canonical source of truth across all the places where we set Python versions
* Updates `./github/workflows` to use this new file to get the canonical Python version
* Bumps the Python version in other places

## Pull request checklist

- [x] Did you test this change locally?
- [ ] Did you update the documentation (if required)?
- [ ] Did you add/update relevant tests for this change (if required)?

### CODE REVIEW

**Review by peytondmurray — APPROVED** [review]
I was wondering if there was any other way to solve this, but this seems reasonable.

The only ones I could find that were missed are the entries in `pyproject.toml`. Do we need to worry about those?

Also the tests are failing, but I think that's from the previous PR that got merged.

**Comment by jaimergp** [comment]
This is a better way of consolidating the information. My two cents:

- There's no standard filename or location for this type of file, but I do see some projects using this filename. There are others like simply `.python-version` (no `-default`).
- Parsing from a plain text file might introduce accidental trailing whitespace. Usually tricky to debug. We could make sure that the file is always whitespace stripped with a pre-commit rule for that file only. Or if there's none, a simply Python step in the workflow:

```yaml
- name: Make sure python-version has no whitespace
  shell: python
  run: |
    from pathlib import Path
    assert Path(".python-version-default").read_text().strip() == Path(".python-version-default").read_text()
```

- The environment.yml file python version might get out of date. There's a comment about it but if someone updates the python-version-default file they might not see the environment.yml one. So I suggest we add a little check step like above:

```yaml
- name: Make sure python-version has no whitespace
  shell: python
  run: |
    from pathlib import Path
    assert f'- python={Path(".python-version-default").read_text().strip()}' in Path("environment.yml").read_text()
```

**Comment by peytondmurray** [comment]
Yep, now that you mention it pre-commit isn't hitting this file with the current configuration. Can we change it to strip trailing whitespace everywhere? I don't actually know of a single situation in which I'd _want_ trailing whitespace.

```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ".*\\.py"
      - id: check-added-large-files
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
```

**Comment by jaimergp** [comment]
And maybe make sure `end-of-file-fixer` doesn't add the extra newline?

**Comment by trallard** [comment]
> Also the tests are failing, but I think that's from the previous PR that got merged.

@peytondmurray No this is the same original error in my PR about the `pip` key rather than from the previous PR

> The environment.yml file python version might get out of date. There's a comment about it but if someone updates the python-version-default file they might not see the environment.yml one. So I suggest we add a little check step like above:

My goal would be to eventually just get rid of `environment.yaml` files; right now, the only one that might be going stale would be the `dev-environment.yaml` as we are otherwise using the `python-default-version` file to set the Python version elsewhere. 

Now if someone uses that locally then that might be out of date 🤷🏽‍♀️  but I see the proposed workflow as already more robust _sans_ the end of file/whitespace thingy.

**Comment by trallard** [comment]
> The only ones I could find that were missed are the entries in pyproject.toml. Do we need to worry about those?

Why would we need to change these? These are the Python requires `3.8` so unless we are dropping `3.8-11` we do not need to change these

**Comment by trallard** [comment]
I fixed the pre-commit hooks, so there should be no need to add extra steps.

> There's no standard filename or location for this type of file, but I do see some projects using this filename. There are others, such as simply .python-version (no default).

Since there is no standard, I used `python-version-default` for symmetry with what we were using in some GH workflows (env variable), but I am not privy to keeping or changing the name in case either of you have a preference @jaimergp @peytondmurray

**Comment by peytondmurray** [comment]
I'm totally fine with `.python-version-default`, and the changes `.pre-commit-config.yml` look good to me. if @jaimergp is okay with it, let's merge. :rocket:

**Comment by trallard** [comment]
Ok will merge.

**Comment by peytondmurray** [comment]
Closes https://github.com/conda-incubator/conda-store/issues/842.

**Pull request merged**
